name: CI_from_hexlet_fork

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run makefile
        run: make setup
      - name: Run lint
        run: make lint
  test:
    runs-on: ubuntu-latest
    steps:
        - name: Run tests
          run: make tests
    
