name: CI_from_hexlet_fork

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run makefile
        run: make setup
  test:
      runs-on: ubuntu-latest
      needs: [setup]
      steps:
      - uses: actions/checkout@v4
      - name: Run test
        run: make test
    
