name: CI_from_hexlet_fork

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run makefile
        run: make setup

  test:
    runs-on: ubuntu-latest
    steps:
         needs: setup
        - name: Run tests
          run: make test
  lint:
    runs-on: ubuntu-latest
        needs: [setup, test]
      - name: Run lint
        run: make lint
    
